services:
  django-app:
    build:
      context: .
      dockerfile: ./audiophile/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./audiophile:/django-app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped

  nextjs-app:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/next-app
    working_dir: /next-app
    command: npm run dev
    restart: unless-stopped
